# Generated by Django 4.2.28 on 2026-03-04 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentsummary_content_hash_documentsummary_model_and_more'),
        ('legistar', '0003_legislation_vote_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislation',
            name='has_amendment_docs',
            field=models.BooleanField(db_index=True, default=False, help_text="True if any supporting document title contains 'amendment'."),
        ),
        migrations.CreateModel(
            name='AmendmentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amendment_number', models.CharField(blank=True, help_text="Parsed amendment identifier, e.g. 'A', '1', '2'.", max_length=50)),
                ('short_title', models.TextField(blank=True, help_text='Brief descriptive title extracted from the amendment text.')),
                ('sponsors', models.JSONField(default=list, help_text='List of sponsor/author names, e.g. [{"name": "Councilmember Rivera"}].')),
                ('effect_statement', models.TextField(blank=True, help_text='Effect Statement extracted from the amendment, attributed to sponsor(s).')),
                ('normative_summary', models.TextField(blank=True, help_text='LLM summary embracing the normative/policy language of the amendment.')),
                ('technical_changes', models.TextField(blank=True, help_text='LLM-generated bulleted list of technical/instrumental changes.')),
                ('votes_json', models.JSONField(default=dict, help_text='Vote records for this amendment: {rows: [{name, vote, district, in_favor, opposed, absent}]}. Empty if no vote data is available.')),
                ('pass_as_amended', models.BooleanField(default=False, help_text="True when no separate amendment vote was recorded; votes_json is populated from the bill's final passage vote, each member labeled 'Pass as Amended'.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(help_text='The supporting document that is the amendment.', on_delete=django.db.models.deletion.CASCADE, related_name='amendment_summaries', to='documents.document')),
                ('legislation', models.ForeignKey(help_text='The council bill this amendment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='amendment_summaries', to='legistar.legislation')),
            ],
            options={
                'verbose_name': 'Amendment summary',
                'verbose_name_plural': 'Amendment summaries',
            },
        ),
        migrations.AddConstraint(
            model_name='amendmentsummary',
            constraint=models.UniqueConstraint(fields=('legislation', 'document'), name='unique_amendment_summary_for_legislation_document'),
        ),
    ]
